--- 
title: "Annual Report for Financial Year 2019-20"
author: "Road Safety & Transport Authority"
date: "July 2020"
subtitle: Ministry of Informations & Communications
colorlinks: yes
lot: yes
lof: yes
fontsize: 12pt
site: bookdown::bookdown_site
documentclass: book
bibliography:
- book.bib
- packages.bib
biblio-style: apalike
link-citations: yes
github-repo: github.com/UgyenNorbu/Annual_Report_2020
url: www.rsta.gov.bt
description: This annual report is published by Road Safety & Transport Authority,
  MoIC.
---

# Year in Review {-}

This Financial Year 2019-20 was a mixed year for the Authority in terms of its performance and achievements.

As the year witnessed the outbreak of covid-19 pandemic, it has, not surprisingly, affected the deliverables of the Authority. In particular, construction and maintenance work were affected due to shortage of labor and material. However, despite the pandemic, the Authority has collected Nu. 420,024,771.15/- (Four hundred Twenty million Twenty Four thousand Seven hundred and Seventy One) in revenue. Bus terminal at Thimphu, Phuentsholing, Gelephu, Samdrupjongkhar and Mongar regional offices has been renovated, 20 additional passenger transport service routes were introduced. The authority also approved Bhutan Airport Shuttle Bus Services (BASS) and Premium Passenger bus service between Thimphu-Paro and Thimphu-Phuentsholing respectively.

The Authority has procured 5 new vehicles replacing the aging pool vehicle fleets which were over decade-and-half old. Further, budget for new uniforms for all eligible staff were secured with Uniform Code and Conduct. This ensures annual budgetary space for annual issuance of the uniform to staff which will foster a sense of belonging among the staff and reinforce professionalism while delivering the Authority’s statutory mandates.

Tashi Delek!  

```{block html.tag='signature', type='flushright'}
Pemba Wangchuk  
**Director General**
```
